; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32doit-devkit-v1

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2

build_flags =
    -DAPP_WIDTH=128
    -DAPP_HEIGHT=64

[env:native_sdl2]
platform = native

build_flags =
    -std=gnu++17
    -DPLATFORM_PC
    -DAPP_WIDTH=128
    -DAPP_HEIGHT=64
    !sdl2-config --cflags
    !sdl2-config --libs

lib_compat_mode = off
lib_deps =
    olikraus/U8g2

build_src_filter =
    +<main_pc.cpp>
    +<*>
    -<main_esp32.cpp>

[env:native_sdl3]
platform = native

build_flags =
    -std=gnu++17
    -DPLATFORM_PC
    -DSDL3
    -DAPP_WIDTH=128
    -DAPP_HEIGHT=64
    !pkg-config --cflags --libs sdl3

lib_compat_mode = off
lib_deps =
    olikraus/U8g2

build_src_filter =
    +<main_pc.cpp>
    +<*>
    -<main_esp32.cpp>
